#include<stdio.h>
#include<string.h>
int main()
{
    int a=0,b=0,c=0,d=0,e=0,f=0,g=0,h=0,i=0,j=0,k=0,l=0,m=0,n=0,o=0,p=0,q=0,r=0,s=0,t=0,u=0,v=0,w=0,x=0,y=0,z=0,i1,num=0;
    char str[100],str2[100];
    gets(str);
    gets(str2);
    for(i1=0;(str[i1])!='\0';i1++)
    {
    switch(str[i1])
    {
        case'a':
        a++;
        break;
        case'b':
        b++;
        break;
        case'c':
        c++;
        break;
         case'd':
        d++;
        break;
         case'e':
        e++;
        break;
         case'f':
        f++;
        break;
         case'g':
        g++;
        break;
         case'h':
        h++;
        break;
         case'i':
        i++;
        break;
         case'j':
        j++;
        break;
         case'k':
        k++;
        break;
         case'l':
        l++;
        break;
         case'm':
        m++;
        break;
         case'o':
        o++;
        break;
         case'p':
        p++;
        break;
         case'q':
        q++;
        break;
         case'r':
        r++;
        break;
         case's':
        s++;
        break;
         case't':
        t++;
        break;
         case'u':
        u++;
        break;
         case'v':
        v++;
        break;
         case'w':
        w++;
        break;
         case'x':
        x++;
        break;
         case'y':
        y++;
        break;
         case'z':
        z++;
        break;
        case'#':
        num=1;
        break;
    }

    if(num==1)
    break;

    }
        for(i1=0;(str2[i1])!='\0';i1++)
          {
    switch(str2[i1])
    {
        case'a':
        a++;
        break;
        case'b':
        b++;
        break;
        case'c':
        c++;
        break;
         case'd':
        d++;
        break;
         case'e':
        e++;
        break;
         case'f':
        f++;
        break;
         case'g':
        g++;
        break;
         case'h':
        h++;
        break;
         case'i':
        i++;
        break;
         case'j':
        j++;
        break;
         case'k':
        k++;
        break;
         case'l':
        l++;
        break;
         case'm':
        m++;
        break;
         case'o':
        o++;
        break;
         case'p':
        p++;
        break;
         case'q':
        q++;
        break;
         case'r':
        r++;
        break;
         case's':
        s++;
        break;
         case't':
        t++;
        break;
         case'u':
        u++;
        break;
         case'v':
        v++;
        break;
         case'w':
        w++;
        break;
         case'x':
        x++;
        break;
         case'y':
        y++;
        break;
         case'z':
        z++;
        break;
        case'#':
        num=1;
        break;
    }

    if(num==1)
    break;
    }
    printf("a %d\nb %d\nc %d\nd %d\ne %d\nf %d\ng %d\nh %d\ni %d\ne %d\nj %d\nk %d\nl %d\nm %d\nn %d\no %d\np %d\nq %d\nr %d\ns %d\nt %d\nu %d\nv %d\nw %d\nx %d\ny %d\nz %d\n",
    a,b,c,d,e,f,g,h,i,e,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z);
}
